import random
import json
maleVoices = ["en-AU-Standard-D","en-IN-Standard-B","en-IN-Standard-C","en-GB-Standard-B","en-GB-Standard-D","en-US-Standard-A","en-US-Standard-B","en-US-Standard-D","en-US-Standard-F","en-US-Standard-I","en-US-Standard-J"]
femaleVoices = ["en-AU-Standard-A","en-AU-Standard-C","en-IN-Standard-A","en-IN-Standard-D","en-GB-Standard-A","en-GB-Standard-C","en-GB-Standard-F","en-US-Standard-C","en-US-Standard-E","en-US-Standard-G","en-US-Standard-H"]
nuetralVoices = femaleVoices + maleVoices
def random_age():
    return random.randint(18, 100)

def random_element(arr):
    return random.choice(arr)
    
Interests = ["love movies, watch new ones every day, while constantly quoting their favorite films.",
"write poetry. Spends hours alone believing that nobody understands them.",
"are afraid of everything. Constantly fears for their life even at the most mundane things.",
"love a good fight. Would do anything to be challenged by a worthy opponent.",
"make EDM music, their music is awful but they refuse to listen to criticism.",
"go hunting every week. Being out there hunting down creatures is the only thing that brings them peace.",
"have 15 cats. They care about their cats more than anything.",
"drink for fun. They can't have a good time without a drink in their hand.",
"are a serial killer. They've been killing for a while and enjoy the rush of taking a life.",
"play video games, they make obnoxious references to video games and tend to be seen as annoying.",
"are a pro swimmer, they can swim faster than most olympic athletes.",
"collect pogs, they think they'll have some sort of value in the future.",
"consider themselves a financial guru. They view their own advice as gospel, and consider anyone that doesn't take it to be an idiot.",
"love horror movies. They want to act in one in the future, and have an unhealthy obsession with all things macabre.",
"sing all the time yet has a terrible memory. Can't remember the words to their favorite songs.",
"are very sleepy, and love to nap.",
]
powers = ["Affinity", "Aversion", "Power Absorption", "Power Augmentation", "Self-Power Augmentation", "Power Bestowal", "Power Detection", "Power Erasure", 
"Power Negation", "Power Randomization", "Power Replication", "Power Restoration", "Powers Via Object", "Superpower Manipulation", "Accelerated Rotation", 
"Additional Limbs", "Adoptive Muscle Memory", "Amalgamation", "Plant Merging", "Solid Merging", "Anatomical Liberation", "Body Part Substitution", "Bone Manipulation",
 "Camouflage", "Claw Retraction", "Deflection", "Fang Retraction", "Fat Manipulation", "Helicopter Propulsion", "Invisibility", "Immobility", "Immutability", "Invulnerability",
  "Jet Propulsion", "Matter Ingestion", "Mobile Invulnerability", "Muscle Manipulation", "Nail Manipulation", "Needle Projection", "Organic Constructs", "Prehensile Hair",
   "Prehensile Tail", "Prehensile Tongue", "Regenerative Healing Factor", "Replication", "Self-Detonation", "Sharp Tail", "Spike Protrusion", "Structure Weakening",
    "Tentacle Manifestation", "Tendril Generation", "Vampire Physiology", "Wallcrawling", "Acid Generation", "Ash Generation", "Bubble Generation", "Dust Generation", 
    "Powder Generation", "Echolocation", "Enhanced Breath", "Fire Breath", "Fire Generation", "Fog Generation", "Goo Generation", "Heat Generation", "Ink Generation", 
    "Miasma Emission", "Chlorine Gas Generation", "Nerve Gas Generation", "Poison Gas Generation", "Oil Generation", "Pheromone Manipulation", "Poison Generation",
     "Scald Generation", "Smoke Generation", "Sonic Scream", "Stench Generation", "Water Generation", "Web Generation", "Aquatic Breathing", "Atmospheric Adaptation",
      "Environmental Adaptation", "Aerial Adaptation", "Arctic Adaptation", "Desert Adaptation", "Fallout Adaptation", "Mountain Adaptation", "Subterranean Adaptation", 
      "Wetland Adaptation", "Poison Immunity", "Reactive Adaptation", "Self-Sustenance", "Thermal Resistance", "Tracking Evasion", "Vacuum Adaptation", "Enhanced Accuracy",
       "Enhanced Agility", "Enhanced Combat", "Enhanced Condition", "Enhanced Crafting", "Enhanced Dexterity", "Enhanced Durability", "Enhanced Flexibility", "Enhanced Leap",
        "Enhanced Lung Capacity", "Enhanced Reflexes", "Enhanced Senses", "Enhanced Hearing", "Enhanced Smell", "Enhanced Synesthesia", "Enhanced Taste", "Enhanced Touch",
         "Enhanced Vision", "Hyper Awareness", "Enhanced Stamina", "Enhanced Strength", "Enhanced Swordsmanship", "Enhanced Thievery", "Enhanced Visibility", "Powerful Bite", 
         "Supernatural Accuracy", "Supernatural Agility", "Supernatural Combat", "Supernatural Condition", "Supernatural Dexterity", "Supernatural Durability", "Supernatural Flexibility", 
         "Supernatural Leap", "Supernatural Reflexes", "Supernatural Senses", "Supernatural Hearing", "Supernatural Smell", "Supernatural Taste", "Supernatural Touch", 
         "Supernatural Vision", "Supernatural Stamina", "Supernatural Strength", "Supernatural Swordsmanship", "Supernatural Thievery", "360-Degree Vision", "Accelerated Vision", 
         "Astral Vision", "Atomic Vision", "Augmented Reality Vision", "Aura Vision", "Blood-Flow Vision", "Caustic Vision", "Chaotic Vision", "Chemo Vision", "Chrono Vision", 
         "Color Vision", "Dark Vision", "Death Vision", "Digital Vision", "Dimensional Vision", "DNA Vision", "Ectoplasmic Vision", "Electromagnetic Vision", "Emotion Vision", 
         "Energy Vision", "Explosion Vision", "Fire Vision", "Freeze Vision", "Gamma Vision", "Graphic Vision", "Healing Vision", "Heat Vision", "Hypnotic Vision",
          "Illusion Vision", "Ionic Vision", "Infrared Vision", "Invisibility Vision", "Kinetic Vision", "Laser Vision", "Life Vision", "Light Vision", "Lightning Vision", 
          "Lunar Vision", "Magic Vision", "Merging Vision", "Microscopic Vision", "Microwave Vision", "Movement Vision", "Multi-Directional Vision", "Multiple Vision",
           "Neon Vision", "Night Vision", "Oil Vision", "Organic Vision", "Photography Vision", "Plasma Vision", "Probability Vision", "Quantum Vision", "Radio Vision", 
           "Radioactive Vision", "Scanner Vision", "Shared Vision", "Slime Vision", "Soundwave Vision", "Supercolor Vision", "Supernatural Vision", "Telekinetic Vision",
            "Telescopic Vision", "Timeline-Shared Vision", "Ultimate Vision", "Ultraviolet Vision", "Wind Vision", "X-Ray Vision", "4th Wall Awareness", "Dual Mind", 
            "Ecological Empathy", "Enhanced Intelligence", "Supernatural Intelligence", "Enhanced Memory", "Enhanced Wits", "Supernatural Wits", "Feral Mind", 
            "Intuitive Aptitude", "Knowledge Replication", "Mentifery", "Omniscience", "Omnilingualism", "Botanical Communication", "Cyber Communication", 
            "Extraterrestrial Communication", "Faunal Communication", "Psychic Navigation", "Psychic Shield", "Technology Manipulation", "Astral Projection", 
            "Claircognizance", "Clairvoyance", "Danger Intuition", "Dimensional Awareness", "Empathy", "Extrasensory Perception", "Mediumship", "Mendacity Detection",
             "Mental Projection", "Offspring Detection", "Precognition", "Abacomancy", "Numerology", "Oneiromancy", "Psychometry", "Retrocognition", "Telepathy",
              "Astral Trapping", "Dream Manipulation", "Emotion Manipulation", "Fear Inducement", "Hypnosis", "Memory Manipulation", "Mental Manipulation", "Mind Control",
               "Mindscape Transportation", "Possession", "Psionic Inundation", "Psychic Constructs", "Siren Song", "Social Cloaking", "Vertigo Inducement", "Vocal Mind Control",
                "Belief Inducement", "Unconsciousness Inducement", "Yin & Yang Manipulation", "Access and Occlusion", "Activation & Deactivation", "Animation", "Cloaking", 
                "Death Inducement", "Dehydration", "Deoxygenation", "Dimensional Storage", "Disintegration", "Emotion Manipulation", "Healing", "Intangibility", 
                "Life-Force Absorption", "Melting", "Mind Exchange", "Paralysis Inducement", "Petrification", "Physical Restoration", "Projected Thermography",
                 "Sedation Inducement", "Self-Spawn", "Age Manipulation", "Aura Manipulation", "Biological Manipulation", "Cosmic Manipulation", "Darkness Manipulation", 
                 "Density Control", "Elemental Transmutation", "Fundamental Forces Manipulation", "Gravity Manipulation", "Jactitation", "Light Manipulation", 
                 "Color Manipulation", "Rainbow Manipulation", "Lunar Manipulation", "Magnetism Manipulation", "Mass Manipulation", "Molecular Manipulation", 
                 "Nerve Manipulation", "Nothingness Manipulation", "Physics Manipulation", "Pressure Manipulation", "Probability Manipulation", "Reality Warping", 
                 "Reanimation", "Solar Manipulation", "Sound Manipulation", "Spatial Manipulation", "Telekinesis", "Temporal Manipulation", "Weight Manipulation",
                  "Circadian Manipulation", "Ink Manipulation", "Literary Manipulation", "Mirror Manipulation", "Oil Manipulation", "Season Manipulation", 
                  "Vector Manipulation", "Air Manipulation", "Smoke Manipulation", "Animal Manipulation", "Amphibian Manipulation", "Arachnid Manipulation", 
                  "Avian Manipulation", "Fish Manipulation", "Insect Manipulation", "Mammal Manipulation", "Reptile Manipulation", "Ash Manipulation", 
                  "Dust Manipulation", "Earth Manipulation", "Crystal Manipulation", "Glass Manipulation", "Magma Manipulation", "Metal Manipulation", 
                  "Sand Manipulation", "Electricity Manipulation", "Electromagnetism Manipulation", "Fire Manipulation", "Ice Manipulation", 
                  "Plant Manipulation ", "Flower Manipulation",
                   "Fruit/Vegetable Manipulation", "Fungus Manipulation", "Nature Manipulation", "Paper Manipulation", "Plant Growth", 
                   "Pollen Manipulation", "Wood Manipulation", "Water Manipulation", "Vapor Manipulation", "Weather Manipulation", "Cloud Manipulation", "Storm Manipulation",
                    "Combustion Inducement", "Concussion Beams", "Energy Absorption", "Energy Constructs", "Energy Conversion", "Energy Emission", 
                    "Energy Negation", "Force-Field Generation", "Kinetic Energy Manipulation", "Life-Force Manipulation", "Light Generation", "Microwave Emission", 
                    "Radiation Manipulation", "Vibration Emission", "Volatile Constructs", "Beacon Emission", "Burrowing", "Cosmic Teleportation", "Dimensional Travel",
                     "Electrical Transportation", "Escape Artistry", "Portal Creation", "Speed Swimming", "Summoning", "Super Speed", "Teleportation", "Time Travel",
                      "Wormhole Creation", "Flight", "Gliding", "Levitation", "Wing Manifestation","Absolute Immortality", "Autopotence", "Higher Consciousness", 
                      "Self Origin Manipulation", "Self-Detonation", "Self-Disintegration", "Self-Molecular Manipulation", "Self-Power Bestowal", "Self-Spawn", "Self-Sustenance",
                       "Self-Transcendence", "Supernatural Self-Preservation", "Illusion Manipulation", "Holographic Projection", "Age Shifting", "Air Mimicry",
                        "Animal Morphing", "Bionic Physiology", "Dermal Armor", "Elasticity", "Malleable Anatomy", "Monster Physiology", "Power Replication", 
                        "Reactive Adaptation", "Shapeshifting", "Size Manipulation", "Water Mimicry", "Air Mimicry", "Darkness Mimicry", "Metal Mimicry", "Gold Mimicry",
                         "Inorganic Mimicry", "Fire Mimicry", "Magma Mimicry", "Sand Mimicry", "Ink Mimicry", "Elemental Mimicry", "Clay Mimicry", "Slime Mimicry",
                          "Smoke Mimicry", "Electricity Mimicry", "Crystal Mimicry", "Diamond Mimicry", "Paper Mimicry", "Digital Form", "Tachyon Mimicry", 
                          "Electromagnetic Wave Physiology", "Ice Mimicry", "Stellar Physiology", "Spatial Mimicry", "Artificially Enhanced Physiology", "Energy Physiology", "Dust Mimicry", "Ash Mimicry", "Animal Morphing", "Amphibian Physiology", "Arachnid Physiology", "Scorpion Physiology", "Spider Physiology", "Avian Physiology", "Corvid Physiology", "Owl Physiology", "Parrot Physiology", "Fish Physiology", "Shark Physiology", "Insect Physiology", "Ant Physiology", "Bee Physiology", "Beetle Physiology", "Blattodea Physiology", "Butterfly Physiology", "Moth Physiology", "Cephalopod Physiology", "Cnidarian Physiology", "Crustacean Physiology", "Echinoderm Physiology", "Mammalian Physiology", "Bat Physiology", "Bovine Physiology", "Camelid Physiology", "Canine Physiology", "Cervid Physiology", "Cetacean Physiology", "Elephant Physiology", "Equid Physiology", "Horse Physiology",
 "Feline Physiology", "Giraffe Physiology", "Hyena Physiology", "Lagomorph Physiology", "Marsupial Physiology", "Mongoose Physiology", "Monotreme Physiology", 
 "Pinniped Physiology", "Primate Physiology", "Procyonid Physiology", "Prosimian Physiology", "Rhinoceros Physiology", "Rodent Physiology", "Sirenia Physiology", 
 "Ursine Physiology", "Xenarthra Physiology", "Parasite Physiology", "Reptilian Physiology", "Dinosaur Physiology", "Dragon Physiology", "Pterosaur Physiology", 
 "Snake Physiology", "Tortoise Physiology", "Turtle Physiology", "Chimerism", "Hybrid Soul", "Mythic Physiology", "Alien Physiology", "Angel Physiology",
  "Bakeneko Physiology", "Demon Physiology", "Elf Physiology", "Fairy Physiology", "Gargoyle Physiology", "Genie Physiology", "Ghost Physiology", "Giant Physiology",
   "Gorgon Physiology", "Griffin Physiology", "Grim Reaper Physiology", "Hellhound Physiology", "Kitsune Physiology", "Merfolk Physiology", "Minotaur Physiology",
    "Monster Physiology", "Naga Physiology", "Nephilim Physiology", "Oni Physiology", "Pegasus Physiology", "Phoenix Physiology", "Raiju Physiology",
     "Sasquatch Physiology", "Spirit Physiology", "Succubus Physiology", "Tengu Physiology", "Thunderbird Physiology", "Troll Physiology", "Undead Physiology", 
     "Unicorn Physiology", "Vampire Physiology", "Wendigo Physiology", "Werewolf Physiology", "Plant Mimicry", "Flower Mimicry", "Fungal Mimicry", "Wood Mimicry",
      "Unicellular Mimicry", "Transcendent Physiology", "Cosmic Entity Physiology", "Cthulhu Mythos Deity Physiology", "Mythic Physiology", "Aboriginal Deity Physiology", 
      "African Deity Physiology", "Altaic Deity Physiology", "Arab Deity Physiology", "Armenian Deity Physiology", "Aztec Deity Physiology", "Canaanite Deity Physiology",
       "Celtic Deity Physiology", "Chinese Deity Physiology", "Egyptian Deity Physiology", "Finnish Deity Physiology", "Greek Deity Physiology", "Protogenoi Physiology", 
       "Titan Physiology", "Guarani Deity Physiology", "Hindu Deity Physiology", "Inca Deity Physiology", "Mayan Deity Physiology", "Mesopotamian Deity Physiology", 
       "Native American Deity Physiology", "Norse Deity Physiology", "Oceanic Deity Physiology", "Orisha Physiology", "Philippine Deity Physiology", "Roman Deity Physiology", 
       "Shinto Deity Physiology", "Siberian Deity Physiology", "Slavic Deity Physiology", "Vodou Deity Physiology", "Zoroastrian Deity Physiology", "Bionic Physiology", 
       "Robotization", "Candy Mimicry", "Computer Virus Physiology", "Empathic Mimicry", "Flat Body", "Garbage Mimicry", "Power Inheritance", "Spring Form", "Storybook Mimicry", 
       "Swamp Mimicry", "Antimatter Manipulation", "Chaos Manipulation", "Complete Arsenal", "Cosmic Telepathy", "Creation", "Ability Creation", "Animal Creation", "Life Creation",
        "Dark Matter Manipulation", "Enigma Force", "Evolution", "Existential Plane Manipulation", "Hell-Fire Manipulation", "Holy Fire Manipulation", "Immortality", "Infinite Supply", 
        "Life-Force Manipulation", "Life-Force Generation", "Logic Manipulation", "Magic", "Alchemy", "Art Magic", "Astrology", "Chaos Magic", "Craftsmanship Magic", "Creation Magic",
         "Curse Inducement", "Dark Arts", "Destruction Magic", "Divination", "Druidic Magic", "Elemental Magic", "Healing", "Illusionary Magic", "Jinx", "Life Magic", "Mysticism",
          "Occultism", "Necromancy", "Ritual Magic", "Shamanism", "Spell Casting", "Theurgy", "Transmutation", "Voodoo", "White Arts", "Mathematics Manipulation", "Matter Manipulation", 
          "Matter Transmutation", "Molecular Manipulation", "Omnilock", "Omnipotence", "Omnipresence", "Omniscience", "Order Manipulation", "Paradox Inducement", "Pathifery",
           "Physics Manipulation", "Plasma Manipulation", "Power Mixture", "Quantum Manipulation", "Science Manipulation", "Spatial Manipulation", "Spatial-Temporal Lock", "Summoning", 
           "Superpower Manipulation", "Terrain Manipulation", "Twilight Manipulation", "Universal Irreversibility", "Vocifery"]
locations = ["walmart", "target","mall","cemetary","military base","Art Gallery", "Ambulance", "Adoption Clinic", "Amazon Rainforest", "Antique Store", 
"Attic", "Barbershop", "Balcony", "Boat", "Bird's Nest", "Blacksmith", "Bakery", "Butterfly Habitat", "Beaver Dam", "Bootcamp", "Castle", "Cat Lady's House", "Chessboard", 
"Cheese Factory", "Classroom Cemetery", "(Inside a) Comic Book", "Chiropractor's Office", "Circus", "Dance Studio", "Dragon's Lair", "Desert", "Deep Sea Diving", 
"Department of Motor Vehicles", "Detention", "Drunk Tank", "Egypt", "Elephant Sanctuary", "Elf's Forest", "Execution Chamber", "Earthquake Preparedness Class", "Ferris Wheel", 
"Fire Station", "Fishing Pond", "Football Stadium", "Future", "Fortune Teller's Shop", "Grocery Store", "Golf Course", "Ghost Town", "Gondola", "Garbage Dump", "Garage", 
"Goldmine", "Gypsy Camp", "Grand Canyon", "Hardware Store", "Helicopter", "Henhouse", "Hogwarts", "Hospital", "Hawaii", "Igloo", "Island (Tropical)", "Iceberg", "Ice Cream Shop", 
"Ice Age", "Jungle", "Jet Pilot's Cockpit", "Judge's Chambers", "Jury Box", "Jewelry Store", "Jurassic Age", "Karate Class", "Karaoke Bar", "Knight's Training Grounds", 
"King Kong's Cage", "Knitting Circle", "Kangaroo Farm", "Lagoon", "Lighthouse", "Library", "LOST (The TV Show)", "Lifeboat", "Lumberjack Camp", "London", "Laundromat",
 "Make-Up Counter", "Marathon Finish Line", "Mechanic's Shop", "Moon", "Mousetrap", "Mummy's Tomb", "(Inside a) Microwave", "Mountain Top", "Nursing Home", "News Station", "Neverland", 
 "Nature Trail", "Nightclub", "Newspaper Office", "Orchestra Pit", "Office Cubicle", "Orchard", "Outback (Australia)", "Open House (Real Estate)", "Optometrist", "Picnic Spot", 
 "Panda Exhibit", "Prom", "Pirate Ship", "Pet Store", "Post Office", "Photography Class", "Police Station", "Queen Elizabeth's Court", "Quiz Show", "Quicksand", "Radio Program", 
 "Restaurant Grand Opening", "Red Carpet (Movie Premiere)", "Riverboat", "(Inside a) Romance Novel", "Robber's Hideout", "Safari", "School Lunchroom", "School Nurse's Office", 
 "Santa's Workshop", "Ski Slope", "Spider Web", "Summer Camp", "Smurf Village", "Softball Game", "Spaceship", "Second-Hand Store", "Submarine", "Stable", "Treehouse", "Travel Agency",
  "Truckstop", "Theater Audition", "Tidepool", "Tribal Ceremony", "Tourist Trap", "Ugly Princess' Birthday Party", "Underground", "Underwater", "Unemployment Office", "Utopian Society", 
  "Vampire's Home", "Volleyball Court", "Volcano", "Voting Booth", "Witch's Cavern", "Warehouse", "White House", "Waterslide Park", "Wrestling Ring", "Wild West", "Woodshop Class", 
  "Wedding Ceremony", "X-Ray Lab", "Xylophone Store", "Yard Sale", "Yoga Class", "Yearbook Club", "Zeppelin (Blimp)", "Zombie Vacation Spot", "Zoo" ]
names = [ "Aaran", "Aaren", "Aarez", "Aarman", 
"Aaron", "Aaron-James", "Aarron", 
"Aaryan", "Aaryn", "Aayan", "Aazaan", 
"Abaan", "Abbas", "Abdallah", "Abdalroof", 
"Abdihakim", "Abdirahman", "Abdisalam", "Abdul", 
"Abdul-Aziz", "Abdulbasir", "Abdulkadir", "Abdulkarem", 
"Abdulkhader", "Abdullah", "Abdul-Majeed", "Abdulmalik", "Abdul-Rehman", "Abdur", "Abdurraheem", "Abdur-Rahman", "Abdur-Rehmaan", "Abel", "Abhinav", "Abhisumant", 
"Abid", "Abir", "Abraham", "Abu", "Abubakar", "Ace", "Adain", "Adam", "Adam-James", "Addison", "Addisson", "Adegbola", "Adegbolahan", "Aden", "Adenn", "Adie", "Adil", 
"Aditya", "Adnan", "Adrian", "Adrien", "Aedan", "Aedin", "Aedyn", "Aeron", "Afonso", "Ahmad", "Ahmed", "Ahmed-Aziz", "Ahoua", "Ahtasham", "Aiadan", "Aidan", "Aiden", 
"Aiden-Jack", "Aiden-Vee", "Aidian", "Aidy", "Ailin", "Aiman", "Ainsley", "Ainslie", "Airen", "Airidas", "Airlie", "AJ", "Ajay", "A-Jay", "Ajayraj", "Akan", "Akram", "Al", 
"Ala", "Alan", "Alanas", "Alasdair", "Alastair", "Alber", "Albert", "Albie", "Aldred", "Alec", "Aled", "Aleem", "Aleksandar", "Aleksander", "Aleksandr", "Aleksandrs", 
"Alekzander", "Alessandro", "Alessio", "Alex", "Alexander", "Alexei", "Alexx", "Alexzander", "Alf", "Alfee", "Alfie", "Alfred", "Alfy", "Alhaji", "Al-Hassan", "Ali", "Aliekber", 
"Alieu", "Alihaider", "Alisdair", "Alishan", "Alistair", "Alistar", "Alister", "Aliyaan", "Allan", "Allan-Laiton", "Allen", "Allesandro", "Allister", "Ally", "Alphonse", "Altyiab", 
"Alum", "Alvern", "Alvin", "Alyas", "Amaan", "Aman", "Amani", "Ambanimoh", "Ameer", "Amgad", "Ami", "Amin", "Amir", "Ammaar", "Ammar", "Ammer", "Amolpreet", "Amos", "Amrinder", "Amrit",
 "Amro", "Anay", "Andrea", "Andreas", "Andrei", "Andrejs", "Andrew", "Andy", "Anees", "Anesu", "Angel", "Angelo", "Angus", "Anir", "Anis", "Anish", "Anmolpreet", "Annan", "Anndra", 
 "Anselm", "Anthony", "Anthony-John", "Antoine", "Anton", "Antoni", "Antonio", "Antony", "Antonyo", "Anubhav", "Aodhan", "Aon", "Aonghus", "Apisai", "Arafat", "Aran", "Arandeep", 
 "Arann", "Aray", "Arayan", "Archibald", "Archie", "Arda", "Ardal", "Ardeshir", "Areeb", "Areez", "Aref", "Arfin", "Argyle", "Argyll", "Ari", "Aria", "Arian", "Arihant", "Aristomenis", 
 "Aristotelis", "Arjuna", "Arlo", "Armaan", "Arman", "Armen", "Arnab", "Arnav", "Arnold", "Aron", "Aronas", "Arran", "Arrham", "Arron", "Arryn", "Arsalan", "Artem", "Arthur", "Artur",
  "Arturo", "Arun", "Arunas", "Arved", "Arya", "Aryan", "Aryankhan", "Aryian", "Aryn", "Asa", "Asfhan", "Ash", "Ashlee-jay", "Ashley", "Ashton", "Ashton-Lloyd", "Ashtyn", "Ashwin", 
  "Asif", "Asim", "Aslam", "Asrar", "Ata", "Atal", "Atapattu", "Ateeq", "Athol", "Athon", "Athos-Carlos", "Atli", "Atom", "Attila", "Aulay", "Aun", "Austen", "Austin", "Avani", 
  "Averon", "Avi", "Avinash", "Avraham", "Awais", "Awwal", "Axel", "Ayaan", "Ayan", "Aydan", "Ayden", "Aydin", "Aydon", "Ayman", "Ayomide", "Ayren", "Ayrton", "Aytug", "Ayub", 
  "Ayyub", "Azaan", "Azedine", "Azeem", "Azim", "Aziz", "Azlan", "Azzam", "Azzedine", "Babatunmise", "Babur", "Bader", "Badr", "Badsha", "Bailee", "Bailey", "Bailie", "Bailley", 
  "Baillie", "Baley", "Balian", "Banan", "Barath", "Barkley", "Barney", "Baron", "Barrie", "Barry", "Bartlomiej", "Bartosz", "Basher", "Basile", "Baxter", "Baye", "Bayley", "Beau", 
  "Beinn", "Bekim", "Believe", "Ben", "Bendeguz", "Benedict", "Benjamin", "Benjamyn", "Benji", "Benn", "Bennett", "Benny", "Benoit", "Bentley", "Berkay", "Bernard", "Bertie", "Bevin", 
  "Bezalel", "Bhaaldeen", "Bharath", "Bilal", "Bill", "Billy", "Binod", "Bjorn", "Blaike", "Blaine", "Blair", "Blaire", "Blake", "Blazej", "Blazey", "Blessing", "Blue", "Blyth", "Bo",
   "Boab", "Bob", "Bobby", "Bobby-Lee", "Bodhan", "Boedyn", "Bogdan", "Bohbi", "Bony", "Bowen", "Bowie", "Boyd", "Bracken", "Brad", "Bradan", "Braden", "Bradley", "Bradlie", "Bradly", 
   "Brady", "Bradyn", "Braeden", "Braiden", "Brajan", "Brandan", "Branden", "Brandon", "Brandonlee", "Brandon-Lee", "Brandyn", "Brannan", "Brayden", "Braydon", "Braydyn", "Breandan", 
   "Brehme", "Brendan", "Brendon", "Brendyn", "Breogan", "Bret", "Brett", "Briaddon", "Brian", "Brodi", "Brodie", "Brody", "Brogan", "Broghan", "Brooke", "Brooklin", "Brooklyn",
    "Bruce", "Bruin", "Bruno", "Brunon", "Bryan", "Bryce", "Bryden", "Brydon", "Brydon-Craig", "Bryn", "Brynmor", "Bryson", "Buddy", "Bully", "Burak", "Burhan", "Butali", "Butchi",
     "Byron", "Cabhan", "Cadan", "Cade", "Caden", "Cadon", "Cadyn", "Caedan", "Caedyn", "Cael", "Caelan", "Caelen", "Caethan", "Cahl", "Cahlum", "Cai", "Caidan", "Caiden", "Caiden-Paul",
      "Caidyn", "Caie", "Cailaen", "Cailean", "Caileb-John", "Cailin", "Cain", "Caine", "Cairn", "Cal", "Calan", "Calder", "Cale", "Calean", "Caleb", "Calen", "Caley", "Calib", "Calin",
       "Callahan", "Callan", "Callan-Adam", "Calley", "Callie", "Callin", "Callum", "Callun", "Callyn", "Calum", "Calum-James", "Calvin", "Cambell", "Camerin", "Cameron", "Campbel",
        "Campbell", "Camron", "Caolain", "Caolan", "Carl", "Carlo", "Carlos", "Carrich", "Carrick", "Carson", "Carter", "Carwyn", "Casey", "Casper", "Cassy", "Cathal", "Cator", "Cavan",
         "Cayden", "Cayden-Robert", "Cayden-Tiamo", "Ceejay", "Ceilan", "Ceiran", "Ceirin", "Ceiron", "Cejay", "Celik", "Cephas", "Cesar", "Cesare", "Chad", "Chaitanya", "Chang-Ha", 
         "Charles", "Charley", "Charlie", "Charly", "Chase", "Che", "Chester", "Chevy", "Chi", "Chibudom", "Chidera", "Chimsom", "Chin", "Chintu", "Chiqal", "Chiron", "Chris", 
         "Chris-Daniel", "Chrismedi", "Christian", "Christie", "Christoph", "Christopher", "Christopher-Lee", "Christy", "Chu", "Chukwuemeka", "Cian", "Ciann", "Ciar", "Ciaran", 
         "Ciarian", "Cieran", "Cillian", "Cillin", "Cinar", "CJ", "C-Jay", "Clark", "Clarke", "Clayton", "Clement", "Clifford", "Clyde", "Cobain", "Coban", "Coben", "Cobi", "Cobie", 
         "Coby", "Codey", "Codi", "Codie", "Cody", "Cody-Lee", "Coel", "Cohan", "Cohen", "Colby", "Cole", "Colin", "Coll", "Colm", "Colt", "Colton", "Colum", "Colvin", "Comghan", 
         "Conal", "Conall", "Conan", "Conar", "Conghaile", "Conlan", "Conley", "Conli", "Conlin", "Conlly", "Conlon", "Conlyn", "Connal", "Connall", "Connan", "Connar", "Connel", 
         "Connell", "Conner", "Connolly", "Connor", "Connor-David", "Conor", "Conrad", "Cooper", "Copeland", "Coray", "Corben", "Corbin", "Corey", "Corey-James", "Corey-Jay", "Cori",
          "Corie", "Corin", "Cormac", "Cormack", "Cormak", "Corran", "Corrie", "Cory", "Cosmo", "Coupar", "Craig", "Craig-James", "Crawford", "Creag", "Crispin", "Cristian", "Crombie",
           "Cruiz", "Cruz", "Cuillin", "Cullen", "Cullin", "Curtis", "Cyrus", "Daanyaal", "Daegan", "Daegyu", "Dafydd", "Dagon", "Dailey", "Daimhin", "Daithi", "Dakota", "Daksh", "Dale",
            "Dalong", "Dalton", "Damian", "Damien", "Damon", "Dan", "Danar", "Dane", "Danial", "Daniel", "Daniele", "Daniel-James", "Daniels", "Daniil", "Danish", "Daniyal", "Danniel",
             "Danny", "Dante", "Danyal", "Danyil", "Danys", "Daood", "Dara", "Darach", "Daragh", "Darcy", "D'arcy", "Dareh", "Daren", "Darien", "Darius", "Darl", "Darn", "Darrach", 
             "Darragh", "Darrel", "Darrell", "Darren", "Darrie", "Darrius", "Darroch", "Darryl", "Darryn", "Darwyn", "Daryl", "Daryn", "Daud", "Daumantas", "Davi", "David", "David-Jay",
              "David-Lee", "Davie", "Davis", "Davy", "Dawid", "Dawson", "Dawud", "Dayem", "Daymian", "Deacon", "Deagan", "Dean", "Deano", "Decklan", "Declain", "Declan", "Declyan",
               "Declyn", "Dedeniseoluwa", "Deecan", "Deegan", "Deelan", "Deklain-Jaimes", "Del", "Demetrius", "Denis", "Deniss", "Dennan", "Dennin", "Dennis", "Denny", "Dennys", "Denon", 
               "Denton", "Denver", "Denzel", "Deon", "Derek", "Derick", "Derin", "Dermot", "Derren", "Derrie", "Derrin", "Derron", "Derry", "Derryn", "Deryn", "Deshawn", "Desmond",
                "Dev", "Devan", "Devin", "Devlin", "Devlyn", "Devon", "Devrin", "Devyn", "Dex", "Dexter", "Dhani", "Dharam", "Dhavid", "Dhyia", "Diarmaid", "Diarmid", "Diarmuid", 
                "Didier", "Diego", "Diesel", "Diesil", "Digby", "Dilan", "Dilano", "Dillan", "Dillon", "Dilraj", "Dimitri", "Dinaras", "Dion", "Dissanayake", "Dmitri", "Doire", 
                "Dolan", "Domanic", "Domenico", "Domhnall", "Dominic", "Dominick", "Dominik", "Donald", "Donnacha", "Donnie", "Dorian", "Dougal", "Douglas", "Dougray", "Drakeo", 
                "Dre", "Dregan", "Drew", "Dugald", "Duncan", "Duriel", "Dustin", "Dylan", "Dylan-Jack", "Dylan-James", "Dylan-John", "Dylan-Patrick", "Dylin", "Dyllan", "Dyllan-James", 
                "Dyllon", "Eadie", "Eagann", "Eamon", "Eamonn", "Eason", "Eassan", "Easton", "Ebow", "Ed", "Eddie", "Eden", "Ediomi", "Edison", "Eduardo", "Eduards", "Edward", "Edwin", 
                "Edwyn", "Eesa", "Efan", "Efe", "Ege", "Ehsan", "Ehsen", "Eiddon", "Eidhan", "Eihli", "Eimantas", "Eisa", "Eli", "Elias", "Elijah", "Eliot", "Elisau", "Eljay", "Eljon", 
                "Elliot", "Elliott", "Ellis", "Ellisandro", "Elshan", "Elvin", "Elyan", "Emanuel", "Emerson", "Emil", "Emile", "Emir", "Emlyn", "Emmanuel", "Emmet", "Eng", "Eniola",
                 "Enis", "Ennis", "Enrico", "Enrique", "Enzo", "Eoghain", "Eoghan", "Eoin", "Eonan", "Erdehan", "Eren", "Erencem", "Eric", "Ericlee", "Erik", "Eriz", "Ernie-Jacks",
                  "Eroni", "Eryk", "Eshan", "Essa", "Esteban", "Ethan", "Etienne", "Etinosa", "Euan", "Eugene", "Evan", "Evann", "Ewan", "Ewen", "Ewing", "Exodi", "Ezekiel", "Ezra", 
                  "Fabian", "Fahad", "Faheem", "Faisal", "Faizaan", "Famara", "Fares", "Farhaan", "Farhan", "Farren", "Farzad", "Fauzaan", "Favour", "Fawaz", "Fawkes", "Faysal", 
                  "Fearghus", "Feden", "Felix", "Fergal", "Fergie", "Fergus", "Ferre", "Fezaan", "Fiachra", "Fikret", "Filip", "Filippo", "Finan", "Findlay", "Findlay-James", "Findlie", 
                  "Finlay", "Finley", "Finn", "Finnan", "Finnean", "Finnen", "Finnlay", "Finnley", "Fintan", "Fionn", "Firaaz", "Fletcher", "Flint", "Florin", "Flyn", "Flynn", "Fodeba", 
                  "Folarinwa", "Forbes", "Forgan", "Forrest", "Fox", "Francesco", "Francis", "Francisco", "Franciszek", "Franco", "Frank", "Frankie", "Franklin", "Franko", "Fraser",
                   "Frazer", "Fred", "Freddie", "Frederick", "Fruin", "Fyfe", "Fyn", "Fynlay", "Fynn", "Gabriel", "Gallagher", "Gareth", "Garren", "Garrett", "Garry", "Gary", "Gavin", 
                   "Gavin-Lee", "Gene", "Geoff", "Geoffrey", "Geomer", "Geordan", "Geordie", "George", "Georgia", "Georgy", "Gerard", "Ghyll", "Giacomo", "Gian", "Giancarlo", "Gianluca",
                    "Gianmarco", "Gideon", "Gil", "Gio", "Girijan", "Girius", "Gjan", "Glascott", "Glen", "Glenn", "Gordon", "Grady", "Graeme", "Graham", "Grahame", "Grant", "Grayson", 
                    "Greg", "Gregor", "Gregory", "Greig", "Griffin", "Griffyn", "Grzegorz", "Guang", "Guerin", "Guillaume", "Gurardass", "Gurdeep", "Gursees", "Gurthar", "Gurveer", 
                    "Gurwinder", "Gus", "Gustav", "Guthrie", "Guy", "Gytis", "Habeeb", "Hadji", "Hadyn", "Hagun", "Haiden", "Haider", "Hamad", "Hamid", "Hamish", "Hamza", "Hamzah", 
                    "Han", "Hansen", "Hao", "Hareem", "Hari", "Harikrishna", "Haris", "Harish", "Harjeevan", "Harjyot", "Harlee", "Harleigh", "Harley", "Harman", "Harnek", "Harold",
                     "Haroon", "Harper", "Harri", "Harrington", "Harris", "Harrison", "Harry", "Harvey", "Harvie", "Harvinder", "Hasan", "Haseeb", "Hashem", "Hashim", "Hassan", 
                     "Hassanali", "Hately", "Havila", "Hayden", "Haydn", "Haydon", "Haydyn", "Hcen", "Hector", "Heddle", "Heidar", "Heini", "Hendri", "Henri", "Henry", "Herbert", 
                     "Heyden", "Hiro", "Hirvaansh", "Hishaam", "Hogan", "Honey", "Hong", "Hope", "Hopkin", "Hosea", "Howard", "Howie", "Hristomir", "Hubert", "Hugh", "Hugo", "Humza", 
                     "Hunter", "Husnain", "Hussain", "Hussan", "Hussnain", "Hussnan", "Hyden", "I", "Iagan", "Iain", "Ian", "Ibraheem", "Ibrahim", "Idahosa", "Idrees", "Idris", 
                     "Iestyn", "Ieuan", "Igor", "Ihtisham", "Ijay", "Ikechukwu", "Ikemsinachukwu", "Ilyaas", "Ilyas", "Iman", "Immanuel", "Inan", "Indy", "Ines", "Innes", "Ioannis",
                      "Ireayomide", "Ireoluwa", "Irvin", "Irvine", "Isa", "Isaa", "Isaac", "Isaiah", "Isak", "Isher", "Ishwar", "Isimeli", "Isira", "Ismaeel", "Ismail", "Israel",
                       "Issiaka", "Ivan", "Ivar", "Izaak", "J", "Jaay", "Jac", "Jace", "Jack", "Jacki", "Jackie", "Jack-James", "Jackson", "Jacky", "Jacob", "Jacques", "Jad", "Jaden", 
                       "Jadon", "Jadyn", "Jae", "Jagat", "Jago", "Jaheim", "Jahid", "Jahy", "Jai", "Jaida", "Jaiden", "Jaidyn", "Jaii", "Jaime", "Jai-Rajaram", "Jaise", "Jak", "Jake", 
                       "Jakey", "Jakob", "Jaksyn", "Jakub", "Jamaal", "Jamal", "Jameel", "Jameil", "James", "James-Paul", "Jamey", "Jamie", "Jan", "Jaosha", "Jardine", "Jared", "Jarell",
                        "Jarl", "Jarno", "Jarred", "Jarvi", "Jasey-Jay", "Jasim", "Jaskaran", "Jason", "Jasper", "Jaxon", "Jaxson", "Jay", "Jaydan", "Jayden", "Jayden-James",
                         "Jayden-Lee", "Jayden-Paul", "Jayden-Thomas", "Jaydn", "Jaydon", "Jaydyn", "Jayhan", "Jay-Jay", "Jayke", "Jaymie", "Jayse", "Jayson", "Jaz", "Jazeb", 
                         "Jazib", "Jazz", "Jean", "Jean-Lewis", "Jean-Pierre", "Jebadiah", "Jed", "Jedd", "Jedidiah", "Jeemie", "Jeevan", "Jeffrey", "Jensen", "Jenson", "Jensyn", 
                         "Jeremy", "Jerome", "Jeronimo", "Jerrick", "Jerry", "Jesse", "Jesuseun", "Jeswin", "Jevan", "Jeyun", "Jez", "Jia", "Jian", "Jiao", "Jimmy", "Jincheng", "JJ", 
                         "Joaquin", "Joash", "Jock", "Jody", "Joe", "Joeddy", "Joel", "Joey", "Joey-Jack", "Johann", "Johannes", "Johansson", "John", "Johnathan", "Johndean", "Johnjay",
                          "John-Michael", "Johnnie", "Johnny", "Johnpaul", "John-Paul", "John-Scott", "Johnson", "Jole", "Jomuel", "Jon", "Jonah", "Jonatan", "Jonathan", "Jonathon", 
                          "Jonny", "Jonothan", "Jon-Paul", "Jonson", "Joojo", "Jordan", "Jordi", "Jordon", "Jordy", "Jordyn", "Jorge", "Joris", "Jorryn", "Josan", "Josef", "Joseph", 
                          "Josese", "Josh", "Joshiah", "Joshua", "Josiah", "Joss", "Jostelle", "Joynul", "Juan", "Jubin", "Judah", "Jude", "Jules", "Julian", "Julien", "Jun", "Junior", 
                          "Jura", "Justan", "Justin", "Justinas", "Kaan", "Kabeer", "Kabir", "Kacey", "Kacper", "Kade", "Kaden", "Kadin", "Kadyn", "Kaeden", "Kael", "Kaelan", "Kaelin",
                           "Kaelum", "Kai", "Kaid", "Kaidan", "Kaiden", "Kaidinn", "Kaidyn", "Kaileb", "Kailin", "Kain", "Kaine", "Kainin", "Kainui", "Kairn", "Kaison", "Kaiwen", 
                           "Kajally", "Kajetan", "Kalani", "Kale", "Kaleb", "Kaleem", "Kal-el", "Kalen", "Kalin", "Kallan", "Kallin", "Kalum", "Kalvin", "Kalvyn", "Kameron", "Kames", 
                           "Kamil", "Kamran", "Kamron", "Kane", "Karam", "Karamvir", "Karandeep", "Kareem", "Karim", "Karimas", "Karl", "Karol", "Karson", "Karsyn", "Karthikeya", 
                           "Kasey", "Kash", "Kashif", "Kasim", "Kasper", "Kasra", "Kavin", "Kayam", "Kaydan", "Kayden", "Kaydin", "Kaydn", "Kaydyn", "Kaydyne", "Kayleb", "Kaylem", 
                           "Kaylum", "Kayne", "Kaywan", "Kealan", "Kealon", "Kean", "Keane", "Kearney", "Keatin", "Keaton", "Keavan", "Keayn", "Kedrick", "Keegan", "Keelan",
                            "Keelin", "Keeman", "Keenan", "Keenan-Lee", "Keeton", "Kehinde", "Keigan", "Keilan", "Keir", "Keiran", "Keiren", "Keiron", "Keiryn", "Keison", "Keith",
                             "Keivlin", "Kelam", "Kelan", "Kellan", "Kellen", "Kelso", "Kelum", "Kelvan", "Kelvin", "Ken", "Kenan", "Kendall", "Kendyn", "Kenlin", "Kenneth", 
                             "Kensey", "Kenton", "Kenyon", "Kenzeigh", "Kenzi", "Kenzie", "Kenzo", "Kenzy", "Keo", "Ker", "Kern", "Kerr", "Kevan", "Kevin", "Kevyn", "Kez", "Khai",
                              "Khalan", "Khaleel", "Khaya", "Khevien", "Khizar", "Khizer", "Kia", "Kian", "Kian-James", "Kiaran", "Kiarash", "Kie", "Kiefer", "Kiegan", 
                              "Kienan", "Kier", "Kieran", "Kieran-Scott", "Kieren", "Kierin", "Kiern", "Kieron", "Kieryn", "Kile", "Killian", "Kimi", "Kingston", "Kinneil", 
                              "Kinnon", "Kinsey", "Kiran", "Kirk", "Kirwin", "Kit", "Kiya", "Kiyonari", "Kjae", "Klein", "Klevis", "Kobe", "Kobi", "Koby", "Koddi", "Koden", 
                              "Kodi", "Kodie", "Kody", "Kofi", "Kogan", "Kohen", "Kole", "Konan", "Konar", "Konnor", "Konrad", "Koray", "Korben", "Korbyn", "Korey", "Kori", 
                              "Korrin", "Kory", "Koushik", "Kris", "Krish", "Krishan", "Kriss", "Kristian", "Kristin", "Kristofer", "Kristoffer", "Kristopher", "Kruz",
                               "Krzysiek", "Krzysztof", "Ksawery", "Ksawier", "Kuba", "Kurt", "Kurtis", "Kurtis-Jae", "Kyaan", "Kyan", "Kyde", "Kyden", "Kye", "Kyel",
                                "Kyhran", "Kyie", "Kylan", "Kylar", "Kyle", "Kyle-Derek", "Kylian", "Kym", "Kynan", "Kyral", "Kyran", "Kyren", "Kyrillos", "Kyro", "Kyron", 
                                "Kyrran", "Lachlainn", "Lachlan", "Lachlann", "Lael", "Lagan", "Laird", "Laison", "Lakshya", "Lance", "Lancelot", "Landon", "Lang", "Lasse",
                                 "Latif", "Lauchlan", "Lauchlin", "Laughlan", "Lauren", "Laurence", "Laurie", "Lawlyn", "Lawrence", "Lawrie", "Lawson", "Layne", "Layton",
                                  "Lee", "Leigh", "Leigham", "Leighton", "Leilan", "Leiten", "Leithen", "Leland", "Lenin", "Lennan", "Lennen", "Lennex", "Lennon", "Lennox",
                                   "Lenny", "Leno", "Lenon", "Lenyn", "Leo", "Leon", "Leonard", "Leonardas", "Leonardo", "Lepeng", "Leroy", "Leven", "Levi", "Levon", "Levy", 
                                   "Lewie", "Lewin", "Lewis", "Lex", "Leydon", "Leyland", "Leylann", "Leyton", "Liall", "Liam", "Liam-Stephen", "Limo", "Lincoln", "Lincoln-John",
                                    "Lincon", "Linden", "Linton", "Lionel", "Lisandro", "Litrell", "Liyonela-Elam", "LLeyton", "Lliam", "Lloyd", "Lloyde", "Loche", "Lochlan", 
                                    "Lochlann", "Lochlan-Oliver", "Lock", "Lockey", "Logan", "Logann", "Logan-Rhys", "Loghan", "Lokesh", "Loki", "Lomond", "Lorcan", "Lorenz", 
                                    "Lorenzo", "Lorne", "Loudon", "Loui", "Louie", "Louis", "Loukas", "Lovell", "Luc", "Luca", "Lucais", "Lucas", "Lucca", "Lucian", "Luciano", "Lucien",
                                     "Lucus", "Luic", "Luis", "Luk", "Luka", "Lukas", "Lukasz", "Luke", "Lukmaan", "Luqman", "Lyall", "Lyle", "Lyndsay", "Lysander", "Maanav", "Maaz", 
                                     "Mac", "Macallum", "Macaulay", "Macauley", "Macaully", "Machlan", "Maciej", "Mack", "Mackenzie", "Mackenzy", "Mackie", "Macsen", "Macy", "Madaki",
                                      "Maddison", "Maddox", "Madison", "Madison-Jake", "Madox", "Mael", "Magnus", "Mahan", "Mahdi", "Mahmoud", "Maias", "Maison", "Maisum", "Maitlind",
                                       "Majid", "Makensie", "Makenzie", "Makin", "Maksim", "Maksymilian", "Malachai", "Malachi", "Malachy", "Malakai", "Malakhy", "Malcolm", "Malik", 
                                       "Malikye", "Malo", "Ma'moon", "Manas", "Maneet", "Manmohan", "Manolo", "Manson", "Mantej", "Manuel", "Manus", "Marc", "Marc-Anthony", "Marcel", 
                                       "Marcello", "Marcin", "Marco", "Marcos", "Marcous", "Marcquis", "Marcus", "Mario", "Marios", "Marius", "Mark", "Marko", "Markus", "Marley", 
                                       "Marlin", "Marlon", "Maros", "Marshall", "Martin", "Marty", "Martyn", "Marvellous", "Marvin", "Marwan", "Maryk", "Marzuq", "Mashhood", "Mason",
                                        "Mason-Jay", "Masood", "Masson", "Matas", "Matej", "Mateusz", "Mathew", "Mathias", "Mathu", "Mathuyan", "Mati", "Matt", "Matteo", "Matthew",
                                         "Matthew-William", "Matthias", "Max", "Maxim", "Maximilian", "Maximillian", "Maximus", "Maxwell", "Maxx", "Mayeul", "Mayson", "Mazin",
                                          "Mcbride", "McCaulley", "McKade", "McKauley", "McKay", "McKenzie", "McLay", "Meftah", "Mehmet", "Mehraz", "Meko", "Melville", "Meshach", 
                                          "Meyzhward", "Micah", "Michael", "Michael-Alexander", "Michael-James", "Michal", "Michat", "Micheal", "Michee", "Mickey", "Miguel", "Mika",
                                           "Mikael", "Mikee", "Mikey", "Mikhail", "Mikolaj", "Miles", "Millar", "Miller", "Milo", "Milos", "Milosz", "Mir", "Mirza", "Mitch", "Mitchel",
                                            "Mitchell", "Moad", "Moayd", "Mobeen", "Modoulamin", "Modu", "Mohamad", "Mohamed", "Mohammad", "Mohammad-Bilal", "Mohammed", "Mohanad", "Mohd",
                                             "Momin", "Momooreoluwa", "Montague", "Montgomery", "Monty", "Moore", "Moosa", "Moray", "Morgan", "Morgyn", "Morris", "Morton", "Moshy", 
                                             "Motade", "Moyes", "Msughter", "Mueez", "Muhamadjavad", "Muhammad", "Muhammed", "Muhsin", "Muir", "Munachi", "Muneeb", "Mungo", "Munir", 
                                             "Munmair", "Munro", "Murdo", "Murray", "Murrough", "Murry", "Musa", "Musse", "Mustafa", "Mustapha", "Muzammil", "Muzzammil", "Mykie", 
                                             "Myles", "Mylo", "Nabeel", "Nadeem", "Nader", "Nagib", "Naif", "Nairn", "Narvic", "Nash", "Nasser", "Nassir", "Natan", "Nate", "Nathan", 
                                             "Nathanael", "Nathanial", "Nathaniel", "Nathan-Rae", "Nawfal", "Nayan", "Neco", "Neil", "Nelson", "Neo", "Neshawn", "Nevan", "Nevin", 
                                             "Ngonidzashe", "Nial", "Niall", "Nicholas", "Nick", "Nickhill", "Nicki", "Nickson", "Nicky", "Nico", "Nicodemus", "Nicol", "Nicolae", 
                                             "Nicolas", "Nidhish", "Nihaal", "Nihal", "Nikash", "Nikhil", "Niki", "Nikita", "Nikodem", "Nikolai", "Nikos", "Nilav", "Niraj", "Niro",
                                              "Niven", "Noah", "Noel", "Nolan", "Noor", "Norman", "Norrie", "Nuada", "Nyah", "Oakley", "Oban", "Obieluem", "Obosa", "Odhran", "Odin", 
                                              "Odynn", "Ogheneochuko", "Ogheneruno", "Ohran", "Oilibhear", "Oisin", "Ojima-Ojo", "Okeoghene", "Olaf", "Ola-Oluwa", "Olaoluwapolorimi",
                                               "Ole", "Olie", "Oliver", "Olivier", "Oliwier", "Ollie", "Olurotimi", "Oluwadamilare", "Oluwadamiloju", "Oluwafemi", "Oluwafikunayomi", 
                                               "Oluwalayomi", "Oluwatobiloba", "Oluwatoni", "Omar", "Omri", "Oran", "Orin", "Orlando", "Orley", "Orran", "Orrick", "Orrin", "Orson", 
                                               "Oryn", "Oscar", "Osesenagha", "Oskar", "Ossian", "Oswald", "Otto", "Owain", "Owais", "Owen", "Owyn", "Oz", "Ozzy", "Pablo", "Pacey", 
                                               "Padraig", "Paolo", "Pardeepraj", "Parkash", "Parker", "Pascoe", "Pasquale", "Patrick", "Patrick-John", "Patrikas", "Patryk", "Paul", 
                                               "Pavit", "Pawel", "Pawlo", "Pearce", "Pearse", "Pearsen", "Pedram", "Pedro", "Peirce", "Peiyan", "Pele", "Peni", "Peregrine", "Peter",
                                                "Phani", "Philip", "Philippos", "Phinehas", "Phoenix", "Phoevos", "Pierce", "Pierre-Antoine", "Pieter", "Pietro", "Piotr", "Porter", 
                                                "Prabhjoit", "Prabodhan", "Praise", "Pranav", "Pravin", "Precious", "Prentice", "Presley", "Preston", "Preston-Jay", "Prinay", "Prince",
                                                 "Prithvi", "Promise", "Puneetpaul", "Pushkar", "Qasim", "Qirui", "Quinlan", "Quinn", "Radmiras", "Raees", "Raegan", "Rafael", "Rafal", 
                                                 "Rafferty", "Rafi", "Raheem", "Rahil", "Rahim", "Rahman", "Raith", "Raithin", "Raja", "Rajab-Ali", "Rajan", "Ralfs", "Ralph", "Ramanas"
                                                 , "Ramit", "Ramone", "Ramsay", "Ramsey", "Rana", "Ranolph", "Raphael", "Rasmus", "Rasul", "Raul", "Raunaq", "Ravin", "Ray", "Rayaan", 
                                                 "Rayan", "Rayane", "Rayden", "Rayhan", "Raymond", "Rayne", "Rayyan", "Raza", "Reace", "Reagan", "Reean", "Reece", "Reed", "Reegan", 
                                                 "Rees", "Reese", "Reeve", "Regan", "Regean", "Reggie", "Rehaan", "Rehan", "Reice", "Reid", "Reigan", "Reilly", "Reily", "Reis", "Reiss",
                                                  "Remigiusz", "Remo", "Remy", "Ren", "Renars", "Reng", "Rennie", "Reno", "Reo", "Reuben", "Rexford", "Reynold", "Rhein", "Rheo", "Rhett",
                                                   "Rheyden", "Rhian", "Rhoan", "Rholmark", "Rhoridh", "Rhuairidh", "Rhuan", "Rhuaridh", "Rhudi", "Rhy", "Rhyan", "Rhyley", "Rhyon", 
                                                   "Rhys", "Rhys-Bernard", "Rhyse", "Riach", "Rian", "Ricards", "Riccardo", "Ricco", "Rice", "Richard", "Richey", "Richie", "Ricky",
                                                    "Rico", "Ridley", "Ridwan", "Rihab", "Rihan", "Rihards", "Rihonn", "Rikki", "Riley", "Rio", "Rioden", "Rishi", "Ritchie", "Rivan",
                                                     "Riyadh", "Riyaj", "Roan", "Roark", "Roary", "Rob", "Robbi", "Robbie", "Robbie-lee", "Robby", "Robert", "Robert-Gordon", 
                                                     "Robertjohn", "Robi", "Robin", "Rocco", "Roddy", "Roderick", "Rodrigo", "Roen", "Rogan", "Roger", "Rohaan", "Rohan", "Rohin", 
                                                     "Rohit", "Rokas", "Roman", "Ronald", "Ronan", "Ronan-Benedict", "Ronin", "Ronnie", "Rooke", "Roray", "Rori", "Rorie", "Rory", 
                                                     "Roshan", "Ross", "Ross-Andrew", "Rossi", "Rowan", "Rowen", "Roy", "Ruadhan", "Ruaidhri", "Ruairi", "Ruairidh", "Ruan", 
                                                     "Ruaraidh", "Ruari", "Ruaridh", "Ruben", "Rubhan", "Rubin", "Rubyn", "Rudi", "Rudy", "Rufus", "Rui", "Ruo", "Rupert", "Ruslan",
                                                      "Russel", "Russell", "Ryaan", "Ryan", "Ryan-Lee", "Ryden", "Ryder", "Ryese", "Ryhs", "Rylan", "Rylay", "Rylee", "Ryleigh", "Ryley",
                                                       "Rylie", "Ryo", "Ryszard", "Saad", "Sabeen", "Sachkirat", "Saffi", "Saghun", "Sahaib", "Sahbian", "Sahil", "Saif", "Saifaddine",
                                                        "Saim", "Sajid", "Sajjad", "Salahudin", "Salman", "Salter", "Salvador", "Sam", "Saman", "Samar", "Samarjit", "Samatar", 
                                                        "Sambrid", "Sameer", "Sami", "Samir", "Sami-Ullah", "Samual", "Samuel", "Samuela", "Samy", "Sanaullah", "Sandro", "Sandy", 
                                                        "Sanfur", "Sanjay", "Santiago", "Santino", "Satveer", "Saul", "Saunders", "Savin", "Sayad", "Sayeed", "Sayf", "Scot", "Scott", 
                                                        "Scott-Alexander", "Seaan", "Seamas", "Seamus", "Sean", "Seane", "Sean-James", "Sean-Paul", "Sean-Ray", "Seb", "Sebastian",
                                                         "Sebastien", "Selasi", "Seonaidh", "Sephiroth", "Sergei", "Sergio", "Seth", "Sethu", "Seumas", "Shaarvin", "Shadow", "Shae", 
                                                         "Shahmir", "Shai", "Shane", "Shannon", "Sharland", "Sharoz", "Shaughn", "Shaun", "Shaunpaul", "Shaun-Paul", "Shaun-Thomas", 
                                                         "Shaurya", "Shaw", "Shawn", "Shawnpaul", "Shay", "Shayaan", "Shayan", "Shaye", "Shayne", "Shazil", "Shea", "Sheafan", "Sheigh",
                                                          "Shenuk", "Sher", "Shergo", "Sheriff", "Sherwyn", "Shiloh", "Shiraz", "Shreeram", "Shreyas", "Shyam", "Siddhant", "Siddharth",
                                                           "Sidharth", "Sidney", "Siergiej", "Silas", "Simon", "Sinai", "Skye", "Sofian", "Sohaib", "Sohail", "Soham", "Sohan", "Sol", 
                                                           "Solomon", "Sonneey", "Sonni", "Sonny", "Sorley", "Soul", "Spencer", "Spondon", "Stanislaw", "Stanley", "Stefan", "Stefano",
                                                            "Stefin", "Stephen", "Stephenjunior", "Steve", "Steven", "Steven-lee", "Stevie", "Stewart", "Stewarty", "Strachan", "Struan",
                                                             "Stuart", "Su", "Subhaan", "Sudais", "Suheyb", "Suilven", "Sukhi", "Sukhpal", "Sukhvir", "Sulayman", "Sullivan", "Sultan", 
                                                             "Sung", "Sunny", "Suraj", "Surien", "Sweyn", "Syed", "Sylvain", "Symon", "Szymon", "Tadd", "Taddy", "Tadhg", "Taegan", 
                                                             "Taegen", "Tai", "Tait", "Taiwo", "Talha", "Taliesin", "Talon", "Talorcan", "Tamar", "Tamiem", "Tammam", "Tanay", "Tane", 
                                                             "Tanner", "Tanvir", "Tanzeel", "Taonga", "Tarik", "Tariq-Jay", "Tate", "Taylan", "Taylar", "Tayler", "Taylor", "Taylor-Jay",
                                                              "Taylor-Lee", "Tayo", "Tayyab", "Tayye", "Tayyib", "Teagan", "Tee", "Teejay", "Tee-jay", "Tegan", "Teighen", "Teiyib",
                                                               "Te-Jay", "Temba", "Teo", "Teodor", "Teos", "Terry", "Teydren", "Theo", "Theodore", "Thiago", "Thierry", "Thom", "Thomas",
                                                                "Thomas-Jay", "Thomson", "Thorben", "Thorfinn", "Thrinei", "Thumbiko", "Tiago", "Tian", "Tiarnan", "Tibet", "Tieran", 
                                                                "Tiernan", "Timothy", "Timucin", "Tiree", "Tisloh", "Titi", "Titus", "Tiylar", "TJ", "Tjay", "T-Jay", "Tobey", "Tobi",
                                                                 "Tobias", "Tobie", "Toby", "Todd", "Tokinaga", "Toluwalase", "Tom", "Tomas", "Tomasz", "Tommi-Lee", "Tommy", "Tomson",
                                                                  "Tony", "Torin", "Torquil", "Torran", "Torrin", "Torsten", "Trafford", "Trai", "Travis", "Tre", "Trent", "Trey", 
                                                                  "Tristain", "Tristan", "Troy", "Tubagus", "Turki", "Turner", "Ty", "Ty-Alexander", "Tye", "Tyelor", "Tylar", "Tyler", 
                                                                  "Tyler-James", "Tyler-Jay", "Tyllor", "Tylor", "Tymom", "Tymon", "Tymoteusz", "Tyra", "Tyree", "Tyrnan", "Tyrone",
                                                                   "Tyson", "Ubaid", "Ubayd", "Uchenna", "Uilleam", "Umair", "Umar", "Umer", "Umut", "Urban", "Uri", "Usman", "Uzair",
                                                                    "Uzayr", "Valen", "Valentin", "Valentino", "Valery", "Valo", "Vasyl", "Vedantsinh", "Veeran", "Victor", "Victory",
                                                                     "Vinay", "Vince", "Vincent", "Vincenzo", "Vinh", "Vinnie", "Vithujan", "Vladimir", "Vladislav", "Vrishin",
                                                                      "Vuyolwethu", "Wabuya", "Wai", "Walid", "Wallace", "Walter", "Waqaas", "Warkhas", "Warren", "Warrick", "Wasif",
                                                                       "Wayde", "Wayne", "Wei", "Wen", "Wesley", "Wesley-Scott", "Wiktor", "Wilkie", "Will", "William", "William-John", 
                                                                       "Willum", "Wilson", "Windsor", "Wojciech", "Woyenbrakemi", "Wyatt", "Wylie", "Wynn", "Xabier", "Xander", "Xavier", 
                                                                       "Xiao", "Xida", "Xin", "Xue", "Yadgor", "Yago", "Yahya", "Yakup", "Yang", "Yanick", "Yann", "Yannick", "Yaseen", 
                                                                       "Yasin", "Yasir", "Yassin", "Yoji", "Yong", "Yoolgeun", "Yorgos", "Youcef", "Yousif", "Youssef", "Yu", "Yuanyu",
                                                                        "Yuri", "Yusef", "Yusuf", "Yves", "Zaaine", "Zaak", "Zac", "Zach", "Zachariah", "Zacharias", "Zacharie",
                                                                         "Zacharius", "Zachariya", "Zachary", "Zachary-Marc", "Zachery", "Zack", "Zackary", "Zaid", "Zain", "Zaine",
                                                                          "Zaineddine", "Zainedin", "Zak", "Zakaria", "Zakariya", "Zakary", "Zaki", "Zakir", "Zakk", "Zamaar", "Zander",
                                                                           "Zane", "Zarran", "Zayd", "Zayn", "Zayne", "Ze", "Zechariah", "Zeek", "Zeeshan", "Zeid", "Zein", "Zen", 
     "Zendel", "Zenith", "Zennon", "Zeph", "Zerah", "Zhen", "Zhi", "Zhong", "Zhuo", "Zi", "Zidane", "Zijie", "Zinedine", "Zion", "Zishan", "Ziya", "Ziyaan", "Zohaib", "Zohair", 
     "Zoubaeir", "Zubair", "Zubayr", "Zuriel"
]
genders = ["female","female","female","female","female","male","male","male","male","male","Agender","genderfluid","Nonbinary"]
circumstances = ["There is a time machine nearby, that the characters are trying to reach","there is a knife that can kill anything on a table nearby", "there is a man in the corner who wants to protect one of the combatants", "one of the characters is trying to protect a loved one", "the characters are fighting over a genies lamp", "one of the characters is a robot"]

def randomVoice(gender):
    if(gender =="male"):
        voice= random.choice(maleVoices)
    elif(gender == "female"):
        voice = random.choice(femaleVoices)
    else:
        voice = random.choice(nuetralVoices)
    return voice
def pronoun(gender):
    if(gender =="male"):
        pronoun = "He / Him"
    elif(gender == "female"):
        pronoun = "She / Her"
    else:
        pronoun = "They / Them"
    return pronoun
class Fighter:
    def __init__(self):
        self.power = random_element(powers)
        self.interests = "They " + random_element(Interests)
        self.gender =random_element(genders)
        self.pronouns = pronoun(self.gender)
        self.name = random_element(names)
        self.age = random_age()
        self.voice = randomVoice(self.gender)

class createFight:
    def __init__(self):
        fighter1 = Fighter()
        fighter2 = Fighter()
        self.fighter1 = fighter1.__dict__
        self.fighter2 = fighter2.__dict__
        self.circumstance = random_element(circumstances)
        self.location = random_element(locations)
        self.prompt = f""" Give me a blow-by-blow rundown of a shounen anime-styled fight between two people.
The first is {fighter1.name}; A {fighter1.gender} {fighter1.age} Year old with the power of: {fighter1.power}. They {fighter1.interests}
The Second is {fighter2.name}; A {fighter2.gender} {fighter2.age} Year old with the power of: {fighter2.power}. They {fighter2.interests}
The battle takes place at a {self.location}.
The fight should involve several conflicting strategies as the two banter against each other and try to outwit one another.
The circumstances for the fight are: {self.circumstance}
The fight should be written in script style, with lots of dialogue between the two. Actions should be accredited under the name NARRATOR.
There must be a winner, and the last line must state who won the fight. The winner is determined by which person is stronger, there is no bias between heroes and villains.  
"""

def initializeFight():


    fight = createFight()
    with open("fight.json", "w") as f:
         json.dump(fight.__dict__, f, ensure_ascii=False, indent=4)
initializeFight()